name: Grading workflow
on:
  push:

  workflow_dispatch:

jobs:
  grade-learner:
    if: github.event_name == 'push' && github.repository != 'githubtraining/exercise-remove-commit-history' && github.event.commits[0].message != 'Initial commit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade gitignore activity
        id: events
        uses: ./.github/actions/check-history-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grading results
        uses: githubtraining/looking-glass-action@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feedback: ${{ steps.events.outputs.reports }}

  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "If you're stuck, this documentation may be helpful; https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository"
